//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesApiRest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosRegistro
    {
        public int Id { get; set; }
        public string Compania { get; set; }
        public string Contacto { get; set; }
        public string Correo { get; set; }
        public string Telefono { get; set; }
    }
}
